[package]
name = "dariotd_simple_ml"
description = "A single-threaded simple machine learning."
version = "1.0.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.x"
